# Generated by Django 5.2.17 on 2026-10-02 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_found', models.DateField(blank=True, null=True)),
                ('location_found', models.CharField(choices=[('Amenity Hall', 'Amenity Hall'), ('Annexe Building', 'Annexe Building'), ('Library', 'Library'), ('Canteen', 'Canteen'), ('Main Building', 'Main Building'), ('GymKhana', 'GymKhana'), ('Parking Lot', 'Parking Lot'), ('Technology Bhavan', 'Technology Bhavan'), ('Workshop-2', 'Workshop-2'), ('Workshop-1', 'Workshop-1'), ('Indus Uni. Commons', 'Indus Uni. Commons'), ('IT Department', 'IT Department'), ('Civil Department', 'Civil Department'), ('Mechanical Department', 'Mechanical Department'), ('Electrical Department', 'Electrical Department'), ('Computer Department', 'Computer Department')], max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('meetup_place', models.CharField(blank=True, max_length=200, null=True)),
                ('meetup_date', models.DateField(blank=True, null=True)),
                ('meetup_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('hod', 'Head of Department (HOD)'), ('student', 'Student')], default='student', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('IT Department', 'IT Department'), ('Civil Department', 'Civil Department'), ('Mechanical Department', 'Mechanical Department'), ('Electrical Department', 'Electrical Department'), ('Computer Department', 'Computer Department')], help_text='Required for HOD role. Leave blank for Principal / Student.', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
